name: chilled_haven
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # state management
  get: ^4.6.5
  retrofit: ^4.0.1
  dio: ^5.0.0
  equatable: ^2.0.5
  json_annotation: ^4.7.0
  cached_network_image: ^3.2.3
  rect_getter: ^1.1.0
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^6.0.0+1
  build_runner: ^2.3.2
  json_serializable: ^6.5.4

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/